version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Get properties
          command: |
                  wget http://whereisdarran.com/austinfeedsme.properties
                  wget http://whereisdarran.com/google-services.json -P base/
                  wget http://whereisdarran.com/google-services.json -P apk/
      - run:
          name: Download Dependencies
          command: |
                  sudo chmod +x gradlew
                  ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build Debug
          command: ./gradlew assembleProdDebug
      - store_artifacts:
          path: app/build/outputs/apk/prod/debug/app-prod-debug.apk
          destination: app-prod-debug.apk
      - run:
          name: Uploading on Beta
          command: ./gradlew crashlyticsUploadDistributionProdDebug